version: "3.9"
services:
  api:
    image: ghcr.io/huebot-iot/hub-core-next:latest
    ports:
      - 3000:3000
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork