# Lib services required in development and production env
version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    container_name: huebot_redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: ghcr.io/huebot-iot/nginx:latest
    container_name: huebot_nginx
    restart: always
    network_mode: "host"

  mqtt:
    image: ghcr.io/huebot-iot/mqtt:latest
    container_name: huebot_mqtt
    restart: always
    volumes:
      - /usr/local/bin/mosquitto/conf.d:/mosquitto/config/conf.d
      - /usr/local/bin/mosquitto/passwd:/etc/mosquitto/passwd
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
