# Lib services required in development and production env
version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    container_name: harness_redis
    restart: always
    ports:
      - "6379:6379"
  nginx:
    image: ghcr.io/harness-iot/nginx:latest
    container_name: harness_nginx
    restart: always
    network_mode: "host"
  mqtt:
    image: ghcr.io/harness-iot/mqtt:latest
    container_name: harness_mqtt
    restart: always
    volumes:
      - /usr/local/bin/mosquitto/conf.d:/mosquitto/config/conf.d
      - /usr/local/bin/mosquitto/passwd:/etc/mosquitto/passwd
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
    ports:
      - "18831:1883"
