# Lib services required in development and production env
# Services that cannot be updated by end user
version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    container_name: huebot_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - huebot-net

  nginx:
    image: ghcr.io/huebot-iot/nginx:latest
    container_name: huebot_nginx
    restart: always
    network_mode: "host"

  mqtt_broker:
    image: ghcr.io/huebot-iot/mqtt:latest
    container_name: huebot_mqtt_broker
    restart: always
    volumes:
      - /usr/local/bin/mosquitto/conf.d:/mosquitto/config/conf.d
      - /usr/local/bin/mosquitto/passwd:/etc/mosquitto/passwd
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
    ports:
      - 18831:1883
    networks:
      - huebot-net

networks:
  huebot-net:
    name: hubNetwork
    driver: bridge
